server:
  port: ${REPORTING_SERVER_PORT:8083}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/edfms}
    username: ${DB_USERNAME:edfms}
    password: ${DB_PASSWORD:edfms}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:edfms}
    password: ${RABBIT_PASSWORD:edfms}
    virtual-host: ${RABBIT_VHOST:edfms}

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    org.springframework.amqp: INFO
    org.hibernate.SQL: WARN
