spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/edfms}
    username: ${DB_USERNAME:edfms}
    password: ${DB_PASSWORD:edfms}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:edfms}
    password: ${RABBIT_PASSWORD:edfms}
    virtual-host: ${RABBIT_VHOST:edfms}

server:
  port: ${RESERVATION_SERVER_PORT:8081}
