spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:edfms}
    password: ${RABBIT_PASSWORD:edfms}
    virtual-host: ${RABBIT_VHOST:edfms}

server:
  port: ${NOTIFICATION_SERVER_PORT:8082}
